#!/usr/bin/env python3
"""routes.json is canonical; verify/deploy only deterministic derived artifacts."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'services/outbox-dispatcher/routes.json'
routes = json.loads(source.read_text())
assert len(routes) == 17
for event, route in routes.items():
    assert re.fullmatch(r'integration\.nse\.[a-z_]+_requested', event)
    assert set(route) == {'token_env', 'worker_slug'}
    assert re.fullmatch(r'nse-[a-z-]+-worker', route['worker_slug'])
    assert route['token_env'] == 'NSE_WORKER_TOKEN'
    assert (ROOT / 'supabase/functions' / route['worker_slug'] / 'index.ts').is_file()
artifacts = {
    ROOT / 'services/outbox-dispatcher/deploy/routes-contract.json': json.dumps(routes, indent=2) + '\n',
    ROOT / 'supabase/functions/outbox-dispatcher/routes.generated.ts':
        '// deno-fmt-ignore-file\n// Generated by scripts/generate_outbox_routes.py; edit services/outbox-dispatcher/routes.json.\n'
        + 'export const ROUTES: Readonly<Record<string, string>> = Object.freeze(\n'
        + json.dumps({event: route['worker_slug'] for event, route in routes.items()}, indent=2)
        + ',\n);\n',
}
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for path, content in artifacts.items():
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'route artifact stale: {path.relative_to(ROOT)}')
    else:
        path.write_text(content)
print('17 canonical routes verified')
