// Synthetic fixtures transcribed from each endpoint's handbook row keys, never UAT data.
import type {
  StpSwpReportsApi,
  StpSwpReportsSource,
} from "./nse_stp_swp_reports.ts";
export const B05_ROWS: Record<StpSwpReportsApi, Record<string, string>> = {
  "STP_REG_REPORT": {
    "status": "SYNTHETIC",
    "member_code": "05418",
    "client_code": "SYNTHETIC1",
    "stp_registration_no": "202501011000001",
    "folio_no": "SYNTHETIC",
    "internal_ref_no": "SYNTHETIC",
    "from_amc_name": "SYNTHETIC",
    "to_amc_name": "SYNTHETIC",
    "from_scheme_name": "SYNTHETIC",
    "to_scheme_name": "SYNTHETIC",
    "stp_registration_date": "01 JAN 2025",
    "stp_start_date": "01 JAN 2025",
    "stp_end_date": "01 JAN 2025",
    "frequency_type": "MONTHLY",
    "trxn_mode": "SYNTHETIC",
    "transfer_amount": "1000",
    "transfer_units": "1000",
    "no_of_transfers": "SYNTHETIC",
    "first_order_todays_flag": "SYNTHETIC",
    "euin_declaration": "SYNTHETIC",
    "euin_number": "SYNTHETIC",
    "sub_br_code": "SYNTHETIC",
    "remarks": "SYNTHETIC",
    "sub_br_arn_code": "SYNTHETIC",
    "buy_sell_type": "SYNTHETIC",
    "from_nse_scheme_code": "SYNTHETIC",
    "to_nse_scheme_code": "SYNTHETIC",
    "email_id": "SYNTHETIC",
    "mobile_no": "SYNTHETIC",
    "member_unique_id": "SYNTHETIC_REF_1",
  },
  "STP_CAN_REPORT": {
    "member_code": "05418",
    "client_code": "SYNTHETIC1",
    "stp_registration_no": "202501011000001",
    "folio_no": "SYNTHETIC",
    "from_amc_name": "SYNTHETIC",
    "to_amc_name": "SYNTHETIC",
    "from_scheme_name": "SYNTHETIC",
    "to_scheme_name": "SYNTHETIC",
    "stp_registration_date": "01 JAN 2025",
    "stp_start_date": "01 JAN 2025",
    "stp_end_date": "01 JAN 2025",
    "frequency": "MONTHLY",
    "trxn_mode": "SYNTHETIC",
    "transfer_amount": "1000",
    "transfer_units": "1000",
    "no_of_transfers": "SYNTHETIC",
    "euin_declaration": "SYNTHETIC",
    "euin_number": "SYNTHETIC",
    "sub_br_code": "SYNTHETIC",
    "remarks": "SYNTHETIC",
    "stp_cancellation_date": "01 JAN 2025",
    "stp_cancelled_by": "SYNTHETIC",
  },
  "STP_INST_DUE_REPORT": {
    "stp_registration_no": "202501011000001",
    "client_name": "SYNTHETIC",
    "folio_no": "SYNTHETIC",
    "internal_ref_no": "SYNTHETIC",
    "stp_registration_date": "01 JAN 2025",
    "amc_name": "SYNTHETIC",
    "from_scheme_name": "SYNTHETIC",
    "to_scheme_name": "SYNTHETIC",
    "frequency_type": "MONTHLY",
    "dp_trans": "SYNTHETIC",
    "transfer_amount": "1000",
    "transfer_units": "1000",
    "due_date": "01 JAN 2025",
    "prev_transfer_date": "01 JAN 2025",
    "no_of_transfer_completed": "SYNTHETIC",
    "first_order_todays_flag": "SYNTHETIC",
    "euin_declaration": "SYNTHETIC",
    "euin_number": "SYNTHETIC",
    "sub_br_code": "SYNTHETIC",
    "remarks": "SYNTHETIC",
    "entry_by": "SYNTHETIC",
  },
  "SWP_REG_REPORT": {
    "status": "SYNTHETIC",
    "member_code": "05418",
    "client_code": "SYNTHETIC1",
    "swp_registration_no": "202501011000001",
    "folio_no": "SYNTHETIC",
    "amc": "SYNTHETIC",
    "scheme_name": "SYNTHETIC",
    "frequency_type": "MONTHLY",
    "swp_registration_date": "01 JAN 2025",
    "swp_start_date": "01 JAN 2025",
    "swp_end_date": "01 JAN 2025",
    "withdrawl_amount": "1000",
    "withdrawal_units": "1000",
    "no_of_withdrawls": "SYNTHETIC",
    "euin_declaration": "SYNTHETIC",
    "euin_number": "SYNTHETIC",
    "subbrcode": "SYNTHETIC",
    "first_order_flag": "SYNTHETIC",
    "int_ref_no": "SYNTHETIC",
    "remark": "SYNTHETIC",
    "sub_broker_arn_code": "SYNTHETIC",
    "nse_scheme_code": "SYNTHETIC",
    "transaction_mode": "SYNTHETIC",
    "mobile_no": "SYNTHETIC",
    "email_id": "SYNTHETIC",
    "bank_account_no": "SYNTHETIC",
    "member_unique_id": "SYNTHETIC_REF_1",
  },
  "SWP_CAN_REPORT": {
    "member_code": "05418",
    "client_code": "SYNTHETIC1",
    "swp_registration_no": "202501011000001",
    "folio_no": "SYNTHETIC",
    "amc": "SYNTHETIC",
    "scheme_name": "SYNTHETIC",
    "swp_registration_date": "01 JAN 2025",
    "swp_cancellation_date": "01 JAN 2025",
    "swp_start_date": "01 JAN 2025",
    "swp_end_date": "01 JAN 2025",
    "frequency_type": "MONTHLY",
    "withdrawl_amount": "1000",
    "withdrawl_units": "1000",
    "no_of_withdrawls": "SYNTHETIC",
    "euin_declaration": "SYNTHETIC",
    "euin_number": "SYNTHETIC",
    "subbrcode": "SYNTHETIC",
    "remark": "SYNTHETIC",
    "swp_cancelled_by": "SYNTHETIC",
    "nse_scheme_code": "SYNTHETIC",
  },
  "SWP_INST_DUE_REPORT": {
    "member_code": "05418",
    "client_code": "SYNTHETIC1",
    "client_name": "SYNTHETIC",
    "swp_regn_no": "202501011000001",
    "folio_no": "SYNTHETIC",
    "internal_ref_no": "SYNTHETIC",
    "regn_date": "01 JAN 2025",
    "amc_name": "SYNTHETIC",
    "scheme_code": "SYNTHETIC",
    "scheme_name": "SYNTHETIC",
    "frequency_type": "MONTHLY",
    "installment_amt": "1000",
    "installment_units": "1000",
    "due_date": "01 JAN 2025",
    "prev_paid_date": "01 JAN 2025",
    "no_of_installments_paid": "SYNTHETIC",
    "total_installment_amt_sold": "1000",
    "unit_sold": "SYNTHETIC",
    "entry_by": "SYNTHETIC",
    "dp_trans": "SYNTHETIC",
    "euin_declaration": "SYNTHETIC",
    "euin_number": "SYNTHETIC",
    "subbrcode": "SYNTHETIC",
    "first_order_flag": "SYNTHETIC",
    "remark": "SYNTHETIC",
  },
  "SIP_AMC_PAUSE_REPORT": {
    "client_code": "SYNTHETIC1",
    "sip_registration_no": "202501011000001",
    "scheme_code": "SYNTHETIC",
    "scheme_name": "SYNTHETIC",
    "amount": "1000",
    "sip_start_date": "01 JAN 2025",
    "sip_end_date": "01 JAN 2025",
    "no_of_instalments_paused": "SYNTHETIC",
    "date_of_activation": "01 JAN 2025",
    "pause_from_date": "01 JAN 2025",
    "pause_to_date": "01 JAN 2025",
    "request_id": "552",
    "entry_by": "SYNTHETIC",
    "modified_date": "01 JAN 2025",
    "modified_instalments": "SYNTHETIC",
  },
};
export const B05_APIS = Object.keys(B05_ROWS) as StpSwpReportsApi[];
export function b05Source(api: StpSwpReportsApi): StpSwpReportsSource {
  const due = api === "STP_INST_DUE_REPORT";
  const row = B05_ROWS[api];
  return {
    operation_id: "10000000-0000-4000-8000-000000000002",
    workspace_id: "10000000-0000-4000-8000-000000000004",
    integration_account_id: "10000000-0000-4000-8000-000000000004",
    api,
    client_code: "SYNTHETIC1",
    pan: "AAAAA0000A",
    today: "2026-10-02",
    selectors: due
      ? {
        mode: "registration",
        rows: [
          Object.fromEntries(
            [
              "stp_registration_no",
              "frequency_type",
              "transfer_amount",
              "transfer_units",
              "folio_no",
              "internal_ref_no",
            ].map((k) => [k, row[k]]),
          ),
        ],
      }
      : { mode: "client", rows: [] },
    request: due
      ? { stp_reg_id: "202501011000001" }
      : api === "SIP_AMC_PAUSE_REPORT"
      ? { client_code: "SYNTHETIC1", modification_type: "PAUSE" }
      : { client_code: "SYNTHETIC1" },
  };
}
export function b05Envelope(
  api: StpSwpReportsApi,
  rows: unknown[] = [B05_ROWS[api]],
): Record<string, unknown> {
  return {
    response_status: "S",
    [
      api === "SIP_AMC_PAUSE_REPORT"
        ? "response_data_total"
        : "report_data_total"
    ]: String(rows.length),
    report_data: rows,
    ...(api === "SIP_AMC_PAUSE_REPORT" ? { error_remark: "" } : {}),
  };
}
