// deno-fmt-ignore-file
// Generated by scripts/generate_outbox_routes.py; edit services/outbox-dispatcher/routes.json.
export const ROUTES: Readonly<Record<string, string>> = Object.freeze(
{
  "integration.nse.ucc_registration_requested": "nse-ucc-registration-worker",
  "integration.nse.ucc_verification_requested": "nse-ucc-reconciliation-worker",
  "integration.nse.order_status_requested": "nse-order-status-worker",
  "integration.nse.prov_orders_requested": "nse-prov-orders-worker",
  "integration.nse.client_readiness_requested": "nse-client-readiness-worker",
  "integration.nse.order_funding_requested": "nse-order-funding-worker",
  "integration.nse.settlement_redemption_requested": "nse-settlement-redemption-worker",
  "integration.nse.sip_xsip_reports_requested": "nse-sip-xsip-reports-worker",
  "integration.nse.stp_swp_reports_requested": "nse-stp-swp-reports-worker",
  "integration.nse.master_download_requested": "nse-master-download-worker",
  "integration.nse.mandate_status_requested": "nse-mandate-status-worker",
  "integration.nse.mandate_registration_requested": "nse-bank-mandate-worker",
  "integration.nse.bank_add_requested": "nse-bank-mandate-worker",
  "integration.nse.bank_del_requested": "nse-bank-mandate-worker",
  "integration.nse.bank_mandate_verify_requested": "nse-bank-mandate-worker",
  "integration.nse.onboarding_kyc_check_requested": "nse-onboarding-kyc-worker",
  "integration.nse.ekyc_registration_requested": "nse-onboarding-kyc-worker"
},
);
